### PR TITLE
go.mod: bump swiss

### LINKED ISSUE #6176: cant build in go 1.27.0
build error:
# github.com/cockroachdb/swiss
/home/peace/gopath/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20251224182025-b0f6560f979b/map.go:286:7: undefined: hashFn
/home/peace/gopath/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20251224182025-b0f6560f979b/map.go:337:14: undefined: getRuntimeHasher
/home/peace/gopath/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20251224182025-b0f6560f979b/map.go:338:22: undefined: fastrand64
/home/peace/gopath/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20251224182025-b0f6560f979b/map.go:600:23: undefined: fastrand64
/home/peace/gopath/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20251224182025-b0f6560f979b/map.go:649:19: undefined: fastrand64
/home/peace/gopath/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20251224182025-b0f6560f979b/map.go:670:20: undefined: fastrand64
/home/peace/gopath/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20251224182025-b0f6560f979b/options.go:30:14: undefined: hashFn

Jira issue: PEBBLE-1473

### PR DESCRIPTION
**Pull request by RaduBerinde**
Bump swiss to the version that supports go 1.27.

Fixes #6176

### CODE REVIEW

**Review by fqazi — APPROVED** [review]
:lgtm:

> @fqazi reviewed 2 files and made 1 comment.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/6177#-:-P-dPLLF4nMM_kdpugPA:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on RaduBerinde).
