### ISSUE TITLE
cant build in go 1.27.0

### ISSUE THREAD

**Issue by peacess** [cockroachdb/pebble#6176]
build error:
# github.com/cockroachdb/swiss
/home/peace/gopath/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20251224182025-b0f6560f979b/map.go:286:7: undefined: hashFn
/home/peace/gopath/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20251224182025-b0f6560f979b/map.go:337:14: undefined: getRuntimeHasher
/home/peace/gopath/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20251224182025-b0f6560f979b/map.go:338:22: undefined: fastrand64
/home/peace/gopath/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20251224182025-b0f6560f979b/map.go:600:23: undefined: fastrand64
/home/peace/gopath/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20251224182025-b0f6560f979b/map.go:649:19: undefined: fastrand64
/home/peace/gopath/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20251224182025-b0f6560f979b/map.go:670:20: undefined: fastrand64
/home/peace/gopath/pkg/mod/github.com/cockroachdb/swiss@v0.0.0-20251224182025-b0f6560f979b/options.go:30:14: undefined: hashFn

Jira issue: PEBBLE-1473

**Comment by RaduBerinde** [comment]
Requires https://github.com/cockroachdb/swiss/pull/52

**Comment by melroy89** [comment]
```bash
GOFLAGS=-tags=untested_go_version
```

Might work in the mean time? But yeah I agree that PR needs to be merged.
