### PR TITLE
db: various DB.SSTables improvements

### PR DESCRIPTION
**Pull request by jbowens**
Add a couple improvements to the DB.SSTables method that powers the crdb_internal.sstable_metrics builtin in Cockroach. Subsequent work up in Cockroach will adopt a custom JSON serialization to improve the ergonomics of working with the builtin

### CODE REVIEW

**Comment by jbowens** [comment]
Removed my datadriven test because it's currently nondeterministic. I'll revive it in the Cockroach repo so that I can test the formatting that will actually be in use by the sstable_metrics builtin.

**Review by RaduBerinde — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/pebble/3840#-:-O4751bmDUReIvv81E-l:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved

**Comment by jbowens** [comment]
TFTR!

**Comment by RaduBerinde** [comment]
Do we need to change something on the CRDB side for this? I'm getting this failure in https://github.com/cockroachdb/cockroach/pull/128930:

```
--- FAIL: TestGetSSTableMetricsSingleNode (0.30s)
    test_log_scope.go:170: test logs captured to: /tmp/cockroach/_tmp/e30705b0a8a518f554ca43ed5739c85a/logTestGetSSTableMetricsSingleNode49896762
    test_log_scope.go:81: use -show-logs to present logs inline
    test_server_shim.go:144: cluster virtualization disabled in global scope due to issue: #76378 (expected label: C-bug)
    generator_builtins_test.go:176: error executing '
                 SELECT * FROM crdb_internal.sstable_metrics(
                         1, 1,
                         (SELECT raw_start_key FROM [SHOW RANGES FROM TABLE t WITH KEYS] LIMIT 1),
                         (SELECT raw_end_key FROM [SHOW RANGES FROM TABLE t WITH KEYS] LIMIT 1))': pq: getting table metrics for node 1 store 1: rpc error: code = Unknown desc = strconv.ParseUint: parsing "": invalid syntax
```

**Comment by RaduBerinde** [comment]
Oh, yeah, I just need to update `Pebble.GetTableMetrics`, no problem.
